config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :bookmarks
  root 'bookmarks#index'
  resources :tags
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
# frozen_string_literal: true

class Bookmark < ApplicationRecord
  belongs_to :user
  has_many :taggings
  has_many :tags, through: :taggings
  validates :url, presence: true, url: true
  validates :title, presence: true
  attr_writer :tag_list

  after_save :save_tags
  before_destroy :destroy_tags

  def tag_list
    @tag_list || generate_tag_list
  end

  private

  def destroy_tags
    tags.each(&:destroy)
  end

  def generate_tag_list
    tags.pluck(:name).join(', ')
  end

  def save_tags
    return unless tag_list

    tag_names = tag_list.split(',').collect { |tag| tag.strip.downcase }.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name:, user:) }
    self.tags = new_or_found_tags
  end
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  belongs_to :user
  has_many :taggings, dependent: :destroy
  has_many :bookmarks, through: :taggings

  def to_s
    name
  end
end

app/models/tagging.rb
# frozen_string_literal: true

class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :bookmark
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookmarks, dependent: :destroy
  has_many :tags, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
# frozen_string_literal: true

class BookmarksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bookmark, only: %i[show edit update destroy]
  before_action :collect_bookmarks, only: %i[index]

  def index
    @bookmarks = filter_bookmarks(params[:filter])
    return unless (tag = params[:tag]).present?

    @bookmarks = @bookmarks.joins(:tags).where('tags.name = ?', tag)
  end

  def show; end

  def new
    @bookmark = current_user.bookmarks.new
  end

  def edit; end

  def create
    @bookmark = current_user.bookmarks.build(bookmark_params)

    return render_error(:new) unless @bookmark.save

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to bookmark_url(@bookmark), notice: 'Bookmark was successfully created.' }
      format.json { render :show, status: :created, location: @bookmark }
    end
  end

  def update
    return render_error(:edit) unless @bookmark.update(bookmark_params)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to bookmark_url(@bookmark), notice: 'Bookmark was successfully updated.' }
      format.json { render :show, status: :ok, location: @bookmark }
    end
  end

  def destroy
    @bookmark.destroy

    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: 'Bookmark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def filter_bookmarks(filter)
    return @bookmarks unless params[:filter].present?

    @bookmarks.joins(:tags)
              .where('bookmarks.description ILIKE :filter OR ' \
                     'bookmarks.title ILIKE :filter OR ' \
                     'bookmarks.url ILIKE :filter OR ' \
                     'tags.name ILIKE :filter',
                     filter: "%#{filter}%")
              .distinct
  end

  def render_error(action)
    respond_to do |format|
      format.html { render action, status: :unprocessable_entity }
      format.json { render json: @bookmark.errors, status: :unprocessable_entity }
    end
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def collect_bookmarks
    @bookmarks = current_user.bookmarks.paginate(page: params[:page], per_page: 5).order('bookmarks.title ASC')
  end

  def bookmark_params
    params.require(:bookmark).permit(:title, :url, :description, :tag_list)
  end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  before_action :authenticate_user!

  def index
    @tags = current_user.tags
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
# frozen_string_literal: true

module BookmarksHelper
end

app/helpers/tags_helper.rb
# frozen_string_literal: true

module TagsHelper
end

app/views/bookmarks/_bookmark.html.erb
<%= turbo_frame_tag bookmark do %>
  <div class="mb-2 mt-2 pb-2 bg-green-100 border border-gray-200 rounded-lg shadow">

    <a href="<%= bookmark.url %>" target="_blank">
      <h2 class="text-3xl bg-green-400 text-white w-auto	p-2 rounded-t-lg">
        <%= bookmark.title.humanize %>
      </h2>
    </a>

    <p class="my-1 p-2">
      <a href="<%= bookmark.url %>" class="underline text-3xl" target="_blank"><%= bookmark.url %></a>
    </p>

    <p class="my-1 p-2">
      <strong class="block font-medium mb-1">Description:</strong>
      <%= bookmark.description %>
    </p>

    <p class="my-1 p-2">
      <% if bookmark.tags.any? %>
        <% bookmark.tags.each do |tag| %>
          <%= link_to tag.name, bookmarks_path(tag: tag.name, filter: params[:filter]), data: { turbo_frame: "_top" }, class: "tag bg-blue-200 text-blue-800 rounded-full px-3 py-1 text-sm ml-2" %>
        <% end %>
      <% end %>
    </p>

    <% if action_name != "show" %>
      <div class="p-2 ">
        <%= link_to "Show this bookmark", bookmark, data: {turbo_frame: "_top"}, class: "rounded-lg py-3 px-5 bg-blue-500 inline-block font-medium text-white hover:bg-blue-600" %>
        <%= link_to "Edit this bookmark", edit_bookmark_path(bookmark), class: "rounded-lg py-3 ml-2 px-5 bg-orange-500 inline-block font-medium text-white hover:bg-orange-600" %>
      </div>  
    <% end %>
  </div>
<% end %>

app/views/bookmarks/_form.html.erb
<%= form_with(id: "bookmark_form", model: bookmark, class: "contents") do |form| %>
  <% if bookmark.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
        <% bookmark.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :url %>
    <%= form.text_field :url, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label "Tag list (comma separated)" %><br />
    <%= form.text_field :tag_list, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 ml-2 px-5 bg-orange-500 inline-block font-medium text-white hover:bg-orange-600" %>
  </div>
<% end %>

app/views/bookmarks/create.turbo_stream.erb
<%= turbo_stream.prepend "bookmarks" do %>
  <%= render @bookmark %>
<% end %>

<%= turbo_stream.replace "bookmark_form" do %>
  <%= render "form",  bookmark: current_user.bookmarks.new %>
<% end %>

app/views/bookmarks/edit.html.erb
<%= turbo_frame_tag @bookmark do %>
    <%= render "form", bookmark: @bookmark %>

    <%= link_to "Show this bookmark", @bookmark, data: {turbo_frame: "_top"}, class: "ml-2 mt-2 rounded-lg py-3 px-5 bg-blue-500 inline-block font-medium text-white hover:bg-blue-600" %>
    <%= link_to "Back to bookmarks", bookmarks_path, data: {turbo_frame: "_top"}, class: "ml-2 mt-2 rounded-lg py-3 px-5 bg-blue-500 inline-block font-medium text-white hover:bg-blue-600" %>
<% end %>

app/views/bookmarks/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  
    <div class="mb-2 b-1">
      <% if params[:tag] && !params[:tag].blank? %>
        <h1 class="font-bold text-4xl">Bookmarks Tagged <%= params[:tag].humanize %> | <%= link_to "Clear Tag Selection", bookmarks_path(filter: params[:filter]), class: "underline" %></h1>
      <% else %>
        <h1 class="font-bold text-4xl">Bookmarks</h1>
      <% end %>
    </div>

    <div class="flex justify-between items-center">

      <%= form_tag(bookmarks_path, method: :get) do %>
        <%= text_field_tag(:filter, params[:filter]) %>
        <%= hidden_field_tag(:tag, params[:tag]) %>
        <%= submit_tag "Filter", class: "inline-block rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
      <% end %>
      <%= link_to "Clear Filter", bookmarks_path(tag: params[:tag]), data: {turbo_frame: "_top"}, class: "rounded-lg py-3 ml-2 px-5 bg-orange-500 inline-block font-medium text-white hover:bg-orange-600" %> 

      <%= link_to "New bookmark", new_bookmark_path, data: {turbo_frame: "new_bookmark"}, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %> 
    </div>

  <%= turbo_frame_tag "new_bookmark" do %>
  <% end %>

  <div id="bookmarks" class="min-w-full">
    <%= render @bookmarks %>
  </div>
  <%= will_paginate  @bookmarks %>

</div>

app/views/bookmarks/new.html.erb
<%= turbo_frame_tag "new_bookmark" do %>
    <%= render "form", bookmark: @bookmark %>
    <%= link_to "Cancel", bookmarks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
<% end %>

app/views/bookmarks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @bookmark %>

    <%= link_to "Back to bookmarks", bookmarks_path, class: "ml-2 mt-2 rounded-lg py-3 px-5 bg-blue-500 inline-block font-medium text-white hover:bg-blue-600" %>
    <%= link_to "Edit this bookmark", edit_bookmark_path(@bookmark), class: "rounded-lg py-3 ml-2 px-5 bg-orange-500 inline-block font-medium text-white hover:bg-orange-600" %>

    <div class="inline-block ml-2">
      <%= button_to "Destroy this bookmark", bookmark_path(@bookmark), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-red-500 text-white font-medium hover:bg-red-600" %>
    </div>
  </div>
</div>

app/views/bookmarks/update.turbo_stream.erb
<%= turbo_stream.update @bookmark do %>
  <%= render @bookmark %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookmarks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="flex items-center justify-between shadow text-white bg-green-400 p-4">
      <div class="text-xl font-bold">Bookmark App</div>
      <nav>
        <% if user_signed_in? %>
          <span class="mr-4"><%= button_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, method: :delete %></span>
        <% else %>
          <span class="mr-4"><%= link_to "Sign in", new_user_session_path %></span>
          <span class="mr-4"><%= link_to "Sign up", new_user_registration_path %></span>
          <span><%= link_to "Reset password", new_user_password_path %></span>
        <% end %>
      </nav>
    </header>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/tags/index.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="text-3xl font-semibold mb-4">All Tags for <%= current_user.email %></h1>

  <ul class="list-disc pl-6">
    <% @tags.each do |tag| %>
      <li class="mb-4">
        <h2 class="text-xl font-medium mb-2"><%= tag.name %></h2>

        <ul class="list-disc pl-6">
          <% tag.bookmarks.each do |bookmark| %>
            <li class="mb-2">
              <strong><%= bookmark.title %></strong> - <%= link_to truncate(bookmark.url, length: 30), bookmark, title: bookmark.url %>
            </li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
</div>